// flow-typed signature: 1290bcd729142c1988a2c56e99e80a7d
// flow-typed version: <<STUB>>/lighthousebot_vhttps://github.com/ebidel/lighthousebot/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lighthousebot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lighthousebot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lighthousebot/builder/server' {
  declare module.exports: any;
}

declare module 'lighthousebot/frontend/lighthouse-ci' {
  declare module.exports: any;
}

declare module 'lighthousebot/frontend/public/app' {
  declare module.exports: any;
}

declare module 'lighthousebot/frontend/server' {
  declare module.exports: any;
}

declare module 'lighthousebot/runlighthouse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lighthousebot/builder/server.js' {
  declare module.exports: $Exports<'lighthousebot/builder/server'>;
}
declare module 'lighthousebot/frontend/lighthouse-ci.js' {
  declare module.exports: $Exports<'lighthousebot/frontend/lighthouse-ci'>;
}
declare module 'lighthousebot/frontend/public/app.js' {
  declare module.exports: $Exports<'lighthousebot/frontend/public/app'>;
}
declare module 'lighthousebot/frontend/server.js' {
  declare module.exports: $Exports<'lighthousebot/frontend/server'>;
}
declare module 'lighthousebot/runlighthouse.js' {
  declare module.exports: $Exports<'lighthousebot/runlighthouse'>;
}
