// flow-typed signature: b44a938a2f7fc8401674cecfa48b8294
// flow-typed version: <<STUB>>/@rematch/core_v^1.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rematch/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rematch/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rematch/core/dist/cjs' {
  declare module.exports: any;
}

declare module '@rematch/core/dist/cjs/rematch' {
  declare module.exports: any;
}

declare module '@rematch/core/dist/cjs/rematch.min' {
  declare module.exports: any;
}

declare module '@rematch/core/dist/esm/rematch' {
  declare module.exports: any;
}

declare module '@rematch/core/dist/umd/rematch' {
  declare module.exports: any;
}

declare module '@rematch/core/scripts/bundles' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rematch/core/dist/cjs/index' {
  declare module.exports: $Exports<'@rematch/core/dist/cjs'>;
}
declare module '@rematch/core/dist/cjs/index.js' {
  declare module.exports: $Exports<'@rematch/core/dist/cjs'>;
}
declare module '@rematch/core/dist/cjs/rematch.js' {
  declare module.exports: $Exports<'@rematch/core/dist/cjs/rematch'>;
}
declare module '@rematch/core/dist/cjs/rematch.min.js' {
  declare module.exports: $Exports<'@rematch/core/dist/cjs/rematch.min'>;
}
declare module '@rematch/core/dist/esm/rematch.js' {
  declare module.exports: $Exports<'@rematch/core/dist/esm/rematch'>;
}
declare module '@rematch/core/dist/umd/rematch.js' {
  declare module.exports: $Exports<'@rematch/core/dist/umd/rematch'>;
}
declare module '@rematch/core/scripts/bundles.js' {
  declare module.exports: $Exports<'@rematch/core/scripts/bundles'>;
}
