// flow-typed signature: f5c38030c70be4690d7b42cb8bdb7fb3
// flow-typed version: <<STUB>>/@rematch/loading_v^1.2.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rematch/loading'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rematch/loading' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rematch/loading/dist/rematch-loading.cjs' {
  declare module.exports: any;
}

declare module '@rematch/loading/dist/rematch-loading.esm' {
  declare module.exports: any;
}

declare module '@rematch/loading/dist/rematch-loading.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rematch/loading/dist/rematch-loading.cjs.js' {
  declare module.exports: $Exports<'@rematch/loading/dist/rematch-loading.cjs'>;
}
declare module '@rematch/loading/dist/rematch-loading.esm.js' {
  declare module.exports: $Exports<'@rematch/loading/dist/rematch-loading.esm'>;
}
declare module '@rematch/loading/dist/rematch-loading.umd.js' {
  declare module.exports: $Exports<'@rematch/loading/dist/rematch-loading.umd'>;
}
